### ISSUE TITLE
hello. please tell me how can I build the project in EXE format?

### ISSUE THREAD

**Issue by mrAyaz** [skybrush-io/skybrush-server#2]
hello. please tell me how can I build the project in EXE format?

**Comment by ntamas** [comment]
Unfortunately we cannot offer support for building packaged, ready-to-use executables of Skybrush as part of the community support package. You can download a pre-compiled executable of the community edition of the server, Live and most other components from https://skybrush.io - these come with limitations in the number of drones that you can connect to at the same time. If you would like to lift the limitations or you are building your own version of Skybrush with modifications, you can contact us via email or through the contact form of the homepage to subscribe for premium support.
