### ISSUE TITLE
Build the skybrush-server compilation environment.

### ISSUE THREAD

**Issue by lv333ming** [skybrush-io/skybrush-server#4]
I am a novice, please tell me how to build a skybrush-server compilation environment under win10.

**Comment by markingle** [comment]
@lv333ming did you ever get your build working?

**Comment by cbugk** [comment]
https://discuss.ardupilot.org/t/running-a-drone-light-show-with-arducopter-and-skybrush/88595

There @ntamas has put up a beautiful guide to run a test with simulator. I have followed it through on Ubuntu.

It requires git and [poetry](https://github.com/python-poetry/install.python-poetry.org) only, so should work on Windows.

**Comment by kazogihara** [comment]
I have written the procedure to run it on windows, if you would like to refer to it.
https://dev.to/kazogihara/how-to-build-skybrush-using-sitl-on-windows-3g5k

**Comment by ntamas** [comment]
Thanks! I cannot edit the post on the ArduPilot discussion forum any more, but I've added a reply at the bottom that links to your post. We'll probably re-post the guide it on the Skybrush website soon and then we'll also link to it from there.
