### ISSUE TITLE
Virtual UAVs, Compiling with Source Code

### ISSUE THREAD

**Issue by ahaider1** [skybrush-io/skybrush-server#6]
Hi,
I am facing as issue where I cannot generate any virtual uavs when compiling using the code from the github repo. Is there a different method or fix for this that I do not know about?
Thanks

**Comment by ntamas** [comment]
You should only need to turn on the `virtual_uavs` extension from the admin area at http://localhost:5000 and it should work.

Please note that the issue tracker on Github is reserved to bugs and feature requests. If you need community support, please join our Discord server instead; see https://skybrush.io/support/
